import assert from 'node:assert/strict';
import {webcrypto} from 'node:crypto';
const saved=new Map();
if(!globalThis.crypto)Object.defineProperty(globalThis,'crypto',{value:webcrypto});
globalThis.localStorage={getItem:k=>saved.get(k)??null,setItem:(k,v)=>saved.set(k,String(v)),removeItem:k=>saved.delete(k)};
globalThis.document={querySelector:()=>null};
let version=0;
const reload=()=>import(`../auth.js?test=${++version}`);
const form=(mode,email,password)=>{const parts={email:{value:email},password:{value:password},error:{hidden:true,textContent:''},button:{disabled:false,textContent:'Continue'}};return {dataset:{mode},querySelector:s=>s==='[name=email]'?parts.email:s==='[name=password]'?parts.password:s==='#auth-error'?parts.error:parts.button,reportValidity:()=>true,reset(){parts.email.value='';parts.password.value=''},parts}};
let auth=await reload();
assert.equal(auth.signedIn(),false);
const password='Only-a-generated-test-password!';
assert.ok(await auth.submitAuth(form('signup','preview@example.com',password)));
assert.equal(auth.signedIn(),true);
assert.equal([...saved.values()].some(v=>v.includes(password)),false,'plaintext password must never be persisted');
const account=JSON.parse(saved.get('elf.account'));
assert.equal(account.verifier.length,64);
assert.equal(account.salt.length,32);
auth=await reload();assert.equal(auth.signedIn(),true,'session survives reload');
auth.completeOnboarding();assert.equal(JSON.parse(saved.get('elf.account')).onboardingComplete,true);
auth.signOut();assert.equal(auth.signedIn(),false);assert.ok(saved.has('elf.account'),'logout retains profile');
auth=await reload();assert.equal(auth.signedIn(),false);
const wrong=form('login','preview@example.com','Wrong-password!');assert.equal(await auth.submitAuth(wrong),null);assert.equal(auth.signedIn(),false);assert.equal(wrong.parts.error.hidden,false);
assert.ok(await auth.submitAuth(form('login','preview@example.com',password)));assert.equal(auth.signedIn(),true);
auth.signOut();saved.set('elf.session',JSON.stringify({accountId:'wrong-id'}));auth=await reload();assert.equal(auth.signedIn(),false,'unrelated session does not restore account');
saved.clear();auth=await reload();localStorage.setItem=()=>{throw new Error('storage blocked')};const blocked=form('signup','preview@example.com',password);assert.equal(await auth.submitAuth(blocked),null);assert.equal(auth.signedIn(),false);assert.equal(blocked.parts.error.hidden,false);
console.log('PASS: registration, hashed credential, reload, logout, incorrect/correct login, session identity, blocked storage');
